---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mirobertod/drone-cloudformation

steps:
  - name: test
    image: golang:1.14
    settings:
      mode: createOrUpdate
      region: eu-west-1
      parallel: false
      batch:
        - stackname: my-database-stack
          template: templates/db.yml
          params:
            - key: environment
              value: staging
        - stackname: my-app-stack
          template: templates/app.yml
          params:
            - key: version
              value: "123"
            - key: environment
              value: staging
    commands:
      - env
      - go run .
