---
kind: pipeline
name: default

steps:
  - name: test
    image: mirobertod/drone-cloudformation:0.1
    settings:
      mode: createOrUpdate
      region: eu-west-1
      parallel: false
      batch:
        - stackname: my-database-stack
          template: templates/db.yml
          params:
            - key: environment
              value: staging
        - stackname: my-app-stack
          template: templates/app.yml
          params:
            - key: version
              value: 123
            - key: environment
              value: staging
    commands:
      - env
      - pwd
      - ls -l
      - go run main.go
