---
kind: pipeline
name: default

steps:
  - name: build-image
    image: debian
    commands:
      - docker build -t ci:1 ./

  - name: test
    image: ci:1
    settings:
      mode: createOrUpdate
      region: eu-west-1
      parallel: false
      batch:
        - stackname: my-database-stack
          template: templates/db.yml
          params:
            - key: environment
              value: staging
        - stackname: my-app-stack
          template: templates/app.yml
          params:
            - key: version
              value: 123
            - key: environment
              value: staging
    commands:
      - env
      - go run main.go
    depends_on:
      - build-image
